### ISSUE TITLE
add-menu-item

### ISSUE THREAD

**Issue by samburgers** [soberwp/intervention#10]
Is there any sense in having an `add-menu-item` function? Could just add it in the regular way, but would be nice and clean to include it with Intervention.

Many thanks!

**Comment by darrenjacoby** [comment]
Hi @samburgers 

Sure, just to add a blank wp-admin page?

**Comment by samburgers** [comment]
My use case is that I need to set a link in the admin menu that goes straight to Edit a particular page (Homepage). I suppose it would just need to be a gateway to this:

https://developer.wordpress.org/reference/functions/add_menu_page/

Cheers!

**Comment by darrenjacoby** [comment]
Cool, so it'll essentially be a wrapper for that function.  I'll take a look closer to the weekend.

**Comment by samburgers** [comment]
Sounds good, thank you again!

**Comment by darrenjacoby** [comment]
@samburgers added in 1.2.0 which I'll be releasing this week.

**Comment by darrenjacoby** [comment]
Added in 1.2.0
https://github.com/soberwp/intervention/blob/master/.github/add-menu-page.md
