### ISSUE TITLE
Post types with "-"

### ISSUE THREAD

**Issue by cb3rnard** [soberwp/intervention#119]
Hello !
First of all, this plugin is fantastic and really usefull. I use it on many website.
Today I stumbled on a little issue, which prevents me from updating theme custom types : the slugs include the symbol '-', which is overwritten with '_' in Intervention. Example : "portfolio-item" or "show-item"
Could it be possible to check for both versions when looking for the existence of a custom type ?
Thanks in advance

**Comment by darrenjacoby** [comment]
Sure, I will take a look and see if I can check for both!

**Comment by cb3rnard** [comment]
Just realized that same goes for taxonomies. Damn themes...

**Comment by darrenjacoby** [comment]
@cb3rnard I'm going to recommend moving registering post types and taxonomies away from Intervention. I want focus on removing things from WordPress versus registering, etc. It feels outside scope to keep the plugin lean.
