### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by 9585999** [soberwp/intervention#13]
Hi, I came across your plugin, a useful thing. As I understand the plugin is more for developers than for the user. Maybe there is an opportunity to install it through the composer, but that he went to the `vendor/soberwp` folder, respectively, connected and worked from there?

I understand that it can be thrown in muplugins so that, but I would like to include it by default in the developed theme as well as the controller ...

Thanks for the answer.

**Comment by darrenjacoby** [comment]
@9585999 

I have had a [similar request](https://github.com/soberwp/models/issues/4) on the Models plugin.  I think the same would apply for Intervention. 

I don't think Intervention is that closely coupled with a theme that is should be a theme dependency. If you're using Bedrock, you can use Composer to install the mu-plugin. 

I'm open to debate though, but I know a lot of users using Intervention may also not use Bedrock or Sage.

**Comment by 9585999** [comment]
@darrenjacoby 

Well probably that that there is a category of people which uses sage and does not use Bedrock, is the basic factor for realization **intervention**/**models**/**bundle** installation in a folder `vendor/soberwp`.

In any case, you can after all give people a choice where to put, for example, if you use Bedrock then `composer require soberwp/plugin`, if you want to put in the topic then for example `composer require soberwp/plugin:sage`.

A real example where this might come in handy: you need to develop a theme/add a specific functionality to an already working site. The site was originally made without the use of Berdock/Sage. Most likely you will not put Bedrock on him, you will take Sage and start working, and here the magic begins: you put **Sage**/**Intervention**/**Models**/**Bundle**, it's fast and convenient and is executed in only 5 commands in the terminal.

**Comment by darrenjacoby** [comment]
@9585999 makes sense, let me see what I can do. 

Essentially all that needs to change is the package.json file and the way it's required, which could be done using an conditional statement. Branching out for a Sage version could work.

**Comment by 9585999** [comment]
@darrenjacoby Thank you for your attention.

**Comment by darrenjacoby** [comment]
Added from 1.2.0

From your Sage theme dir
```
composer require soberwp/intervention:1.2.0-p
```

**Comment by 9585999** [comment]
@darrenjacoby Nice, Thank you!

**Comment by darrenjacoby** [comment]
No prob, going to add to Models and Bundle too.
