### ISSUE TITLE
Remove Toolbar Frontend

### ISSUE THREAD

**Issue by renatonascalves** [soberwp/intervention#16]
Not sure if that's the intention but if I set up to show the tool bar in the user profile: `intervention('remove-toolbar-frontend');` has no effect.

I presume it would overide what a user might add there.

**Comment by darrenjacoby** [comment]
Thanks, will take a look at this.

**Comment by darrenjacoby** [comment]
@renatonascalves 

I can confirm it's working on my end, could you provide more information? You could try run this function within your functions.php to debug and see if it works? 

```php
add_filter('show_admin_bar', '__return_false');
```

The module for this function is very basic—
https://github.com/soberwp/intervention/blob/master/src/Module/RemoveToolbarFrontend.php

**Comment by renatonascalves** [comment]
@darrenjacoby Hi!

If you add the mentioned one above, it works. If I remove the above and add in intervention one, it doesn't work as expected. :/

**Comment by darrenjacoby** [comment]
@renatonascalves could you try with the intervention function and specify an user role? 

eg. 
intervention('remove-toolbar-frontend', 'administrator'); 

(depending on the user role, or is it perhaps a custom user role you're using?)

**Comment by renatonascalves** [comment]
Sorry! Forgot to come back and provide my feedback. That error still applies.

It seems user settings takes precedence. The same doesn't happen if one uses the function without checking the user role though.

**Comment by darrenjacoby** [comment]
@renatonascalves 

I'm still unable to replicate. Could you provide more information? Perhaps a GitHub link? 

Are you perhaps using a custom user role? Do other modules work as expected that require user roles?

**Comment by renatonascalves** [comment]
Strange! Really strange! I tried these:

`intervention( 'remove-toolbar-frontend');`
`intervention( 'remove-toolbar-frontend', 'editor' );`
`intervention( 'remove-toolbar-frontend', 'administratot' );`

None of them work. Only when I add like that: `add_filter( 'show_admin_bar', '__return_false' );`

**Comment by darrenjacoby** [comment]
That is strange. If you could provide a link to the project I could try debug from there. Just to ask, are the other modules working (that have user role options) ?

**Comment by darrenjacoby** [comment]
@renatonascalves 

Just checking in here?

**Comment by 9585999** [comment]
Works for me.

Option in the admin panel is enabled, the toolbar is not displayed in the frontend.

**Comment by darrenjacoby** [comment]
Same, I haven't been able to replicate no matter what I've tried.

**Comment by renatonascalves** [comment]
@darrenjacoby I decided to keep using `add_filter( 'show_admin_bar', '__return_false' );` I can't make it work with the intervention one. :)
