### ISSUE TITLE
Remove new WordPress Widgets

### ISSUE THREAD

**Issue by Log1x** [soberwp/intervention#17]
Hey.

Could we get support added to remove the new WordPress widgets? Akismet would also be nice since it's included by default.

New widgets include Audio, Custom HTML, Image, and Video.

**Comment by darrenjacoby** [comment]
@Log1x thanks for bringing to my attention. 

I've included in the new release of Intervention, which I'll push up soon.

**Comment by Log1x** [comment]
Thanks!

**Comment by darrenjacoby** [comment]
Added in 1.2.0
https://github.com/soberwp/intervention/blob/master/.github/remove-widgets.md
