### ISSUE TITLE
remove_menu_page(): E_WARNING: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by connerbw** [soberwp/intervention#21]
`remove_menu_page()` sometimes : E_WARNING: Invalid argument supplied for foreach()

Problematic code: 
```
function remove_menu_page( $menu_slug ) {
  global $menu;
  foreach ( $menu as $i => $item ) {
  // ...
```

URL	/wp/wp-admin/admin-ajax.php
HTTP referrer	https://_SOME_SITE_/wp/wp-admin/network/users.php

Stack trace:
```
/vendor/soberwp/intervention/src/Module/RemoveMenuItems.php (121)
/web/wp/wp-includes/class-wp-hook.php (286)
/web/wp/wp-includes/class-wp-hook.php (310)
/web/wp/wp-includes/plugin.php (453)
/web/wp/wp-admin/admin-ajax.php (44)
```

Offending line:
https://github.com/soberwp/intervention/blob/7d69c58b32fce29aad08e4ff9c9de43963122610/src/Module/RemoveMenuItems.php#L121                 

Possible reason: `global $menu` not defined?   

Upstream bug report:
https://core.trac.wordpress.org/ticket/43714

**Comment by darrenjacoby** [comment]
Seems like a WP issue, so closing for now.

**Comment by losderpos** [comment]
Fixed doing this:
```
if (function_exists('\Sober\Intervention\intervention') && !(defined('DOING_AJAX') && DOING_AJAX)) {
    intervention('remove-menu-items', 'posts', 'all');
}
```
