### ISSUE TITLE
feature request for clean wp_head

### ISSUE THREAD

**Issue by hexcross** [soberwp/intervention#23]
Awesome plugin along with models!! Thanks.

I have idea to few improvements:
1. add support to remove wp-embed
2. add suport to clean wp_head meta tags
3. add support to hide comments from topbar in admin

**Comment by darrenjacoby** [comment]
I will take a look at getting these added when I have a chance. I'm also open to a PR on any of the above.

**Comment by darrenjacoby** [comment]
Thanks for your suggestion, it will be included for the next major release.
