### ISSUE TITLE
A user with multiple roles confuses `remove-toolbar-frontend`

### ISSUE THREAD

**Issue by neilgilmour** [soberwp/intervention#29]
I have added `intervention('remove-toolbar-frontend', 'all-not-admin');` and it removes the toolbar when a user has a role other than admin (excellent!) even when that user ALSO has an admin role (boo!).

It's an edge case so I'm flagging it up for interest really.

The following snippet works for admins who also have other roles
```
/* *
 *
 * Remove admin bar for all users except admin
 */

add_action('after_setup_theme', 'remove_admin_bar');

function remove_admin_bar() {
    if (!current_user_can('administrator') && !is_admin()) {
        show_admin_bar(false);
    }
}
```

**Comment by darrenjacoby** [comment]
Thanks @neilgilmour , I'll be re-working the ways roles are used with Intervention for an upcoming major release and will keep this in mind.
