### ISSUE TITLE
Remove update_footer

### ISSUE THREAD

**Issue by Soean** [soberwp/intervention#3]
To remove the version and the update message from the admin footer, this filter should be added to a module:

`remove_filter( 'update_footer', 'core_update_footer' );`

**Comment by darrenjacoby** [comment]
RemoveUpdateNotices would be the correct module, does the filter only remove the version number and update nag from the footer?

**Comment by Soean** [comment]
Okay.

Yes, `core_update_footer()` only adds the message to the footer:
https://developer.wordpress.org/reference/functions/core_update_footer/

**Comment by darrenjacoby** [comment]
Big thanks for your improvements @Soean !
