### ISSUE TITLE
unable to remove plugins options page

### ISSUE THREAD

**Issue by voyou-sbeaulieu** [soberwp/intervention#30]
We are using the `intervention('remove-menu-items');` to remove all the "danger-item" but there some Dev plugins pages we want to remove here an example : 

Custom Post Type UI ([https://en-ca.wordpress.org/plugins/custom-post-type-ui/](url)) plugins create a options page with this URL:`/wp-admin/admin.php?page=cptui_manage_post_types`

We tried to target this page to hide it without success like so : 

```
intervention('remove-menu-items', ['admin.php?page=cptui_manage_post_types', ], 'admin_client');
//OR
intervention('remove-menu-items', ['cptui_manage_post_types', ], 'admin_client');
``` 

Is there a way to manually remove a page from the admin or they need to be in the list of config?

Thank for your time

**Comment by darrenjacoby** [comment]
@voyou-sbeaulieu long overdue, but did you get this working?

**Comment by darrenjacoby** [comment]
Should work with upcoming version 2.0.0 (there is no config list, only an array of roles)
