### ISSUE TITLE
New realease

### ISSUE THREAD

**Issue by pacotole** [soberwp/intervention#35]
The last release is from 26 Aug 2017.

Please, release a new version with latest fixes included.

**Comment by darrenjacoby** [comment]
Hi @pacotole , I plan on releasing a new version soon. I was going to create a new major version with new features, etc, but I can also do a release with the latest fixes prior. I will look into this soon.

**Comment by darrenjacoby** [comment]
Long overdue, but 1.3.0 has been released. Thanks for your patience, Intervention is going to be getting a lot more love moving forward.
