### ISSUE TITLE
[wp-admin.comments.all] has 'appearance' in the docs example :)

### ISSUE THREAD

**Issue by grahammtbr** [soberwp/intervention#40]
What the title says.

**Comment by grahammtbr** [comment]
Found more errors in the docs, I'll close this and post a full list of what I find after I'm done creating my config file.

**Comment by grahammtbr** [comment]
Another one I saw is under [wp-admin.posts]. It has 'pages' instead of 'posts' under Options.

**Comment by darrenjacoby** [comment]
Thanks @grahammtbr , corrected!
