### ISSUE TITLE
Setting applies to wp-admin-{any-role-here} affects Super Admin.

### ISSUE THREAD

**Issue by grahammtbr** [soberwp/intervention#41]
Like the title says, any settings applied to 'wp-admin.any-role' gets applied to super admin accounts. Regular admin accounts work as expected. I tested all roles (editor, author, etc.)

**Comment by darrenjacoby** [comment]
Thanks for testing @grahammtbr , it's a big help.

I have replaced the user role conditional which had `current_user_can()`, would you mind re-testing? https://github.com/soberwp/intervention/blob/master/src/Intervention.php#L111-L113

**Comment by grahammtbr** [comment]
That fixed it! Closing.
