### ISSUE TITLE
[application.posts]

### ISSUE THREAD

**Issue by bognarlaszlo** [soberwp/intervention#43]
Hi guys!

It looks like in the `intervention/src/Application/Support/Posttypes/Register.php` the `setSupports` method is broken.

It returns this:
```
object(Tightenco\Collect\Support\Collection)#1561 (1) {
  ["items":protected]=>
  array(1) {
    [0]=>
    string(8) "supports"
  }
}
```

Instead of something like this:
```
array(2) {
  [0]=>
  string(5) "title"
  [1]=>
  string(6) "editor"
}
```

**Comment by darrenjacoby** [comment]
@bognarlaszlo thanks, I will take a look into this!

**Comment by darrenjacoby** [comment]
@bognarlaszlo are you modifying an existing post type, or creating a new one? New one if I'm correct?

**Comment by bognarlaszlo** [comment]
Hi, I am creating a new one. The relevant part of the `intervention.php` looks like this:

```
    'application' => [
        'posts' => [
            'post' => false,
            'service' => [
                'one' => 'Service',
                'many' => 'Services',
                'menu_icon' => 'dashicons-clipboard',
                'supports' => ['title', 'editor'],
                'show_in_rest' => true
            ]
        ]
    ]
```

**Comment by darrenjacoby** [comment]
Thanks, can confirm the issue. I have pushed a fix to dev-master if you want to give it a go.

[Fix register post type supports array](https://github.com/soberwp/intervention/commit/7b9c73263ab36d41a6dcf19bf313b2fdb8869184#diff-99e7358da92c4ba8da69d861d8cd75876a8d3f5ab1acd52a14dafb01f01c3a5b)

**Comment by bognarlaszlo** [comment]
@darrenjacoby Thanks for the quick fix. Sorry for being late to reply. I can verify it works as expected.
