### ISSUE TITLE
Possible to rewrite base slugs?

### ISSUE THREAD

**Issue by smeedijzer-internet** [soberwp/intervention#44]
Hi,

Is it possible to rewrite base slugs, like `search_base`, with this plugin?

**Comment by darrenjacoby** [comment]
You can rewrite category and tag base slugs ([https://github.com/soberwp/intervention/blob/master/.github/application/permalinks.md](https://github.com/soberwp/intervention/blob/master/.github/application/permalinks.md)), but not search currently.

I like the idea of also being able to change the search slug so will add it in for a future release.

**Comment by darrenjacoby** [comment]
Added in `permalinks.search-base` to dev-master, so feel free to give it a go. 

[Permalinks search-base](https://github.com/soberwp/intervention/commit/551234c5c9b506f8c91520932ea100bf69b63801#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26)

**Comment by smeedijzer-internet** [comment]
Thanks, it works as expected!

I created a drat pull request for adding extra rewrite bases:

https://github.com/soberwp/intervention/pull/45

**Comment by darrenjacoby** [comment]
Nice, thanks! I'll take a look and see if I can get it merged.

**Comment by darrenjacoby** [comment]
@smeedijzer-internet I've been on summer vacation (southern hemisphere!) but will take a look at this soon.

**Comment by smeedijzer-internet** [comment]
Summer vacation, that nice during corona times!

**Comment by darrenjacoby** [comment]
Ha, well, a very limited at home summer vacation I should say. Heard the NL has been getting tough on the restrictions.

**Comment by darrenjacoby** [comment]
I'm closing this for now and will refer to the PR once more thoroughly reviewed.

**Comment by smeedijzer-internet** [comment]
> Ha, well, a very limited at home summer vacation I should say. Heard the NL has been getting tough on the restrictions.

Yeah, we are in lockdown now till a least 9 februari. I hope there will be less restrictions when spring comes here.

I think something went wrong with the draft pull, I created it again.
