### ISSUE TITLE
Composer error when used with WooCommerce on v. 1.3

### ISSUE THREAD

**Issue by erikhartin** [soberwp/intervention#47]
Hey!

Intervention 1.3 seems to break when used in conjunction with WooCommerce and Bedrock.

To reproduce:

1. create new bedrock: `composer create-project roots/bedrock`
2. install Intervention: `composer require soberwp/intervention`
3. install woocommerce: `composer require woocommerce/woocommerce`

After the usual mess of Woocommerce deprececation notices composer fails with message:
> Installation failed, reverting ./composer.json to its original content.
> 
> [RuntimeException]
> Could not scan for classes inside "/Users/erik/Sites/bedrock-test/web/app/plugins/intervention/src/modules" which does not appear to be a file nor a folder

It works with 2.0.0-rc.1. 

Is this version stable enough for use in production?

**Comment by darrenjacoby** [comment]
I would recommend using 2.0.0-rc1. I'm using it in multiple production sites already. I will tag a stable release towards the end of this month, with very minimal to no changes.
