### ISSUE TITLE
[application.posts] plural form is automatic; won't use parameter

### ISSUE THREAD

**Issue by jrgd** [soberwp/intervention#49]
Heya; 

custom post types are using the auto-pluralised rather than the 'many' parameters

I'm trying to get to use the french plural (Lieux) I specify in the config/intervention.php (cf below), but it just outputs the auto-pluralised version (Lieus) in the admin menu:
- in the LHS menu, in the admin 
- in the header listing my single classes in the admin edit.php?post_type=places

```
            'places' => [
                'one' => 'Lieu',
                'many' => 'Lieux',
            ]
```

**Comment by darrenjacoby** [comment]
Thanks @jrgd , I will look into this. Admittedly the post types module could use some more refining.

**Comment by jrgd** [comment]
looks like this PR https://github.com/soberwp/intervention/pull/48 solves both this issue and the one I referred to on root's slack (about links multiple taxonomies in an array)

**Comment by jrgd** [comment]
can confirm the PR https://github.com/soberwp/intervention/pull/48 is solving both issues (thank you guys!)

**Comment by darrenjacoby** [comment]
Thanks, I'll close this issue and merge PR #48
