### ISSUE TITLE
[wp-admin.common.adminbar.user]

### ISSUE THREAD

**Issue by bigskillet** [soberwp/intervention#50]
Admin bar user options are not being removed.

**Intervention: 2.0.0-rc.1
WordPress: 5.6**

`common.adminbar.user.[howdy, avatar, profile, edit]`

**Comment by bigskillet** [comment]
Never mind... it just dawned on me that those are options, not an array, and that I should remove the brackets.

`common.adminbar.user.howdy`

**Comment by darrenjacoby** [comment]
Yea! I can look into making that clearer in the docs.

You can also pass `common.adminbar.user => ['howdy', 'avatar', 'profile', 'edit]` if you want to group them.
