### ISSUE TITLE
wp_register_script called incorrectly error - v. 2.0.0rc1

### ISSUE THREAD

**Issue by grahammtbr** [soberwp/intervention#51]
I keep getting this error message on 2.0.0rc1 (from master) when editing/creating a new a page/post that's using the Gutenberg editor.

`Notice: wp_register_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the intervention-block-editor handle. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in /var/www/html/wp-includes/functions.php on line 5311`

It appears once when editing a post/page, and is repeating three times when creating a new one. This error is also generated when creating a new CPT page using the classic editor:

`Notice: WP_Block_Type_Registry::register was called incorrectly. Block type "sober/intervention-block-editor" is already registered. Please see Debugging in WordPress for more information. (This message was added in version 5.0.0.) in /var/www/html/wp-includes/functions.php on line 5311`

I've narrowed the offending functions to **posts.item.trackbacks**, **posts.item.discussion**, and **pages.item.discussion**, all under **wp-admin.all**.

**Comment by darrenjacoby** [comment]
@grahammtbr thanks for reporting! I was able to replicate and have pushed a fix. [036e6a3](https://github.com/soberwp/intervention/commit/036e6a3b950e4e9861f310ffe3695c3993868b5b)

**Comment by darrenjacoby** [comment]
Hey @grahammtbr just checking in to see if you've had a moment to check if it's working now on your end?

**Comment by grahammtbr** [comment]
Hi @darrenjacoby sorry no, my ISP supplied me with a bad modem and I was without internet until yesterday. I'll be testing it today!

**Comment by grahammtbr** [comment]
@darrenjacoby Can confirm the fix is working correctly on my sites.

**Comment by darrenjacoby** [comment]
No problem! Thanks so much, and good to hear everything is working now.
