### ISSUE TITLE
posts.all.title throws php errors and ajax errors

### ISSUE THREAD

**Issue by grahammtbr** [soberwp/intervention#52]
I have another one for you, when setting 'posts.all.title' => 'title' I get the following php error,

`Notice: Undefined index: post_type in /var/www/html/wp-content/plugins/intervention-master/src/Admin/Posts/All.php on line 113`

and when running Query Monitor I get the following php ajax error in the browser console on the All Posts page that continues to repeat every 10 seconds or so,

`Object { key: "6cca9fbdd5457d43a614d4f7f4251b6f", type: "notice", message: "Undefined index: post_type", file: "wp-content/plugins/intervention-master/src/Admin/Posts/All.php", line: 113, stack: (5) […], component: "Plugin: intervention-master" }`
![post-type-title-ajax-error](https://user-images.githubusercontent.com/16689388/106335343-7a594880-6241-11eb-9a25-6d05e23eda9e.png)

It also does not set the menu title, even when using 'posts.all.title.menu', and it sets the page title of **all** post types to the new posts title (Pages and CPT's). I've attached a couple screenshots for reference.

![post-type-title-error2](https://user-images.githubusercontent.com/16689388/106335329-73323a80-6241-11eb-871b-b97a9e4727c3.png)
![post-type-title-error](https://user-images.githubusercontent.com/16689388/106335336-76c5c180-6241-11eb-90e6-d5a198f6a360.png)

This does not occur when setting 'pages.all.title', however it does not change the Pages menu title, even when specifying it with 'pages.all.title.menu'.

**Comment by darrenjacoby** [comment]
@grahammtbr 

Thanks for picking this up. I had some issues when initially developing this feature actually, particularly across post types.

I have separated the `x.title.menu` and `x.title.page` which allows me to check for those keys individually rather.

Do you mind testing? [59eb5ccf263ad64f1c6fedeafaf2d5e41de3f059](https://github.com/soberwp/intervention/commit/59eb5ccf263ad64f1c6fedeafaf2d5e41de3f059)

**Comment by grahammtbr** [comment]
Hi @darrenjacoby, sorry for the late reply. I tested and the errors are gone :)
