### ISSUE TITLE
PHP error (notice) when adding a new page/post/cpt

### ISSUE THREAD

**Issue by grahammtbr** [soberwp/intervention#54]
There's always one more... LOL I get this a notice in Query Monitor when adding a **new** page/post/cpt. I don't get it when editing an existing post.

`WP_Block_Type_Registry::register was called incorrectly. Block type "sober/intervention-block-editor" is already registered. Please see Debugging in WordPress for more information. (This message was added in version 5.0.0.)`

**Comment by darrenjacoby** [comment]
@grahammtbr hah, thanks for testing so much, it's been a big help! 

Do you mind sending through the intervention config for this one? Looks like the same error that was happening for the block editor under posts/pages.

**Comment by grahammtbr** [comment]
Here's my config:

```
return [
    'application' => [
        'site' => [
            'membership'    => false,
            'default-role'  => 'editor',
            'timezone'      => 'America/Vancouver',
            'date-format'   => 'F j, Y',
            'time-format'   => 'g:i a',
            'week-starts'   => 'Sun',
        ],
        'writing' => [
            'emoji' => false,
        ],
        'discussion' => [
            'post.ping-flag' => false,
            'post.ping-status' => false,
            'post.comments' => false,
            'avatars' => false,
        ],
        'media' => [
            'mimes.svg' => true,
        ],
    ],
    'wp-admin.all' => [
        'common.adminbar.wp',
        'common.adminbar.comments',
        'common.adminbar.user.howdy' => 'Hello,',
        'common.adminbar.user.avatar',
        'common.adminbar.user.profile',
        'common.footer.credit' => 'Created for 900 Degrees Wood-Fired Pizza by AMT Marketing.',
        'common.tabs.help',
        'dashboard.home.welcome',
        'dashboard.home.notices',
        'dashboard.home.activity',
        'dashboard.home.right-now',
        'dashboard.home.recent-comments',
        'dashboard.home.incoming-links',
        'dashboard.home.plugins',
        'dashboard.home.quick-draft',
        'dashboard.home.drafts',
        'dashboard.home.news',
        'comments',
        'comments.all',
        'posts.title' => 'Blog',
        'posts.all.title.page' => 'Blog Posts',
        'posts.all.title.menu' => 'All Blog Posts',
        'posts.item.trackbacks',
        'posts.item.discussion',
        'pages.item.discussion',
    ],
];
```

**Comment by darrenjacoby** [comment]
@grahammtbr , struggling to replicate this side. Have you got the latest version? This [commit](https://github.com/soberwp/intervention/commit/036e6a3b950e4e9861f310ffe3695c3993868b5b) should have the fix.

**Comment by grahammtbr** [comment]
Okay, I just realized that this only occurs on my local dev environment (docker, specifically [10up's docker](https://github.com/10up/wp-local-docker-v2)). So not a true issue, but still odd.

**Comment by darrenjacoby** [comment]
Just wondering, does the error go away if you remove only
“pages.item.discusssion” from the config?

**Comment by grahammtbr** [comment]
Yes, commenting out “pages.item.discussion" removes the error.

**Comment by darrenjacoby** [comment]
And if you remove only “posts.item.discussion”, and put
“pages.item.discussion” back, does the error come back?

Sorry, debugging through you here to try provide a possible solution.

**Comment by darrenjacoby** [comment]
I ended up re-working the block editor enqueue and adding in some checks to avoid enqueuing multiple times. [623bb1c08c709cfe8d3361062c0a1ad5d82e0f4f](https://github.com/soberwp/intervention/commit/623bb1c08c709cfe8d3361062c0a1ad5d82e0f4f)

**Comment by grahammtbr** [comment]
Hey, sorry for the late reply. I updated with the latest commit, and it fixed the issue. Thanks for that!

**Comment by darrenjacoby** [comment]
No problem! Thanks for always reporting and bringing to my attention. If you find anything else let me know!
