### ISSUE TITLE
Doesn't work on multisite install

### ISSUE THREAD

**Issue by grahammtbr** [soberwp/intervention#56]
Like the title says. No errors or anything, just didn't work.

Not a big deal for me, I just rolled that client back to ver. 1.3, it's fine on that version with WP's infinite backwards compatibility :smile:

**Comment by darrenjacoby** [comment]
Hey @grahammtbr ,

So this is an interesting one. I'm assuming you're using a 'super' administrator user, viewing multisite dashboards. WordPress seems to not pass any user roles for the super administrator role, or administrator role on a network level, so we're left with an empty `$current_user->roles` array, and therefore Intervention doesn't apply the config file. Using `wp-admin.all` actually still did work as it bypasses checking for user roles.

I pushed a fix to add the user role `administrator` manually if the array is empty and multisite is activated, [2285826](https://github.com/soberwp/intervention/commit/2285826104db234fb35959ba68b1ede6178cef2d). Give it a go and let me know if it solves the above issue for you!

**Comment by grahammtbr** [comment]
Thanks Darren. I could have sworn I tried `wp-admin-all` and it didn't work, but I tried it again (with the some version) and it worked... I must have been asleep at the wheel. 

Thanks for all your work on this, it's definitely appreciated. It's the config file I always wanted to create, but never got around to!

**Comment by darrenjacoby** [comment]
@grahammtbr hah, it happens! So, to confirm, the latest fix (on `dev-master`) is working as well with `wp-admin.administrator`? I want to make sure you get the role capabilities on multisite too. It's a pleasure, and thank you for the nice words!

**Comment by darrenjacoby** [comment]
Hey @grahammtbr , just checking if it's all working and I can close the issue?

**Comment by grahammtbr** [comment]
Sorry, missed this. Yes, it's working. Thanks!
