### ISSUE TITLE
Notice: Undefined index: post 

### ISSUE THREAD

**Issue by tablufc88** [soberwp/intervention#58]
Sorry to post issues twice in a couple of days. I was using version 1.2 for a while and finally decided to upgrade yesterday. When updating a post or page, I'm getting the following errors. Any ideas why?

`Notice: Undefined index: post in /srv/www/site/current/web/app/plugins/intervention/src/Admin/Posts/Edit.php on line 97`

`Notice: Undefined index: post in /srv/www/site/current/web/app/plugins/intervention/src/Admin/Pages/Edit.php on line 96`

**Comment by darrenjacoby** [comment]
Absolutely no problem! I appreciate you taking the time to report any issues.

Are you using dev-master (not `2.0.0-rc1/2`)? Could you pass on intervention config for me? 

My guess is that this check is throwing the error; `$_GET['post']`, but just want to confirm that you're on dev-master as there was a similar issue reported on `2.0.0-rc1/2`

**Comment by darrenjacoby** [comment]
I haven't been able to replicate locally, but I have added in further checks for 'post'. [cb23723](https://github.com/soberwp/intervention/commit/f333b6a143a60a17d1cea2dcd88784b9ccbaeaa1)

Please pull down dev-master and let me know if that works in getting rid of the notice.

**Comment by tablufc88** [comment]
Thanks mate. All good now.

**Comment by darrenjacoby** [comment]
Thanks for confirming!
