### ISSUE TITLE
Remove customize does not work as expected (remove cutomizer link wont work in intervention 2)

### ISSUE THREAD

**Issue by emanueljacob** [soberwp/intervention#59]
As far as I understand it, one can remove the customizer link by using something like this (roots/bedrock, intervention 2 (master), sage 10 via config/intervention.php, Wordpress 5.6.1):

`config/intervention.php`

```php
<?php

return [
    'wp-admin.all' => [
        'appearance.customize',
    ],
];
```

although, this disables the customizer functionality, it __does not remove the customizer menu link__.
If that is the expected behavior we should update the corresponding readme.md file. if not there might be a bug.

At least the removal of the parent menu works as expected, so I consider my understanding of the mechanism as correct (?) - the following works for me and removes the 'design' (= appearance) menu item completely:

```php
<?php

return [
    'wp-admin.all' => [
        'appearance',
    ],
];
```

---

How can I remove the customizer link entirely?

the "plain" vairant without using intervention could look like this example:
```php
add_action( 'admin_menu', function () {
    global $submenu;

    if ( isset( $submenu[ 'themes.php' ] ) ) {
        foreach ( $submenu[ 'themes.php' ] as $index => $menuItem ) {
            if ( in_array( 'customize', $menuItem ) ) {
                unset( $submenu[ 'themes.php' ][ $index ] );
            }
        }
    }
});
```

**Comment by darrenjacoby** [comment]
Hi @emanueljacob ,

Thanks for reporting. You're correct in your thinking that `appearance.customize` should remove the submenu item. WordPress throws in a `?return=` for the customizer page so I have created a fix to account for that. I have pushed a fix onto dev-master which should resolve, [4189186].(https://github.com/soberwp/intervention/commit/4189186daaebd14e26a2a5cc20d3442bfd92112d)

 Please let me know if that works now.

**Comment by emanueljacob** [comment]
@darrenjacoby 
Thank you for your awesomely fast reply! Yes, your changes seems to fix it.

btw: I was confused, seeing composer not updating the master, even after `composer clear-cache` until I realized that the master is not yet published to packagist in its latest state... when are you usually push the master to packagist (didn't see any automatic action for that)? is there an eta for a stable version 2.0.0, yet?

**Comment by darrenjacoby** [comment]
No problem! 

Ah, that's painful, I see I had to re-allow Packagist access to this organisation on GH. Not sure why that had changed, but updates should be syncing again now.

There's still two changes I want to make before tagging a stable 2.0.0, namely renaming `application.site` to `application.general` to match the WordPress UI, and address https://github.com/soberwp/intervention/issues/55 

I should be able to wrap those changes possibly as soon as next week, no later than early to mid March I imagine.
