### ISSUE TITLE
Removing the blog (posts) from wp-admin cause edit.php redirect error on all post types.

### ISSUE THREAD

**Issue by grahammtbr** [soberwp/intervention#60]
As the title says. I'm on the latest master, but this is the first time I've tried to remove the default posts, so don't know if it's a newly introduced bug or not.

`'wp-admin.all' => [
    'posts',
]`

**Comment by darrenjacoby** [comment]
Interesting issue, not sure if this is new to be honest. No real code changes around the Router though, so I don't think so. I pushed up a right now. [a830b21](https://github.com/soberwp/intervention/commit/a830b21da225e3e42132df01bd50c5572caad7de)

**Comment by grahammtbr** [comment]
Thanks, fixed! Closing.
