### ISSUE TITLE
Language not changing

### ISSUE THREAD

**Issue by huubl** [soberwp/intervention#61]
Hi,

I try to set the default language to dutch in version: 2.0.0-rc.2 with the config below:

```
return [
    'application' => [
        'general' => [
            [...]
            'language' => 'nl_NL',
            'timezone' => 'Europe/Amsterdam',
            'date-format' => 'j F Y',
            'time-format' => 'H:i',
            'week-starts' => 'Mon',
    ],
     [...]
];
```

Somehow the language is not changing, you know why?

**Comment by darrenjacoby** [comment]
Hey @huubl ,

Changing language in WordPress programatically is a bit of a pain, I almost left it out of Intervention, but it's using this function, [`switch_to_locale()`.](https://developer.wordpress.org/reference/functions/switch_to_locale/)

Basically, the language needs to be installed first. You will be able to see from the list below. It's not ideal, but after some further research it seemed like the best way to change languages programatically.

![image](https://user-images.githubusercontent.com/15921694/112138959-d2298580-8bda-11eb-9a76-24b9ca8acdae.png)

**Comment by huubl** [comment]
@darrenjacoby thanks. I think I found a solution, see https://github.com/soberwp/intervention/pull/62

**Comment by darrenjacoby** [comment]
Oh, amazing, thanks so much! I'll test later and merge.

**Comment by huubl** [comment]
No problem :) 

I looked at [this post](https://wordpress.stackexchange.com/a/318385/180842) and WPML [classes/localization/class-wpml-download-localization.php#L23-L56](https://github.com/oandermedia/plugin-sitepress-multilingual-cms/blob/4ffc227ec9db73b2c2118448d16194b6a3596437/classes/localization/class-wpml-download-localization.php#L23-L56)

**Comment by darrenjacoby** [comment]
Thank you for the research and getting that sorted @huubl !
