### ISSUE TITLE
Gutenberg editor in custom post type

### ISSUE THREAD

**Issue by dooke** [soberwp/intervention#63]
Hello,

Great work this code is awesome!

I have a problem with the options show_in_rest
According to the documentation https://developer.wordpress.org/reference/functions/register_post_type/ if we set this option the post type will be available in block editor.

Do you have an issue / solution for this.

Thanks a lot ;)

**Comment by darrenjacoby** [comment]
Hi @dooke ,

Thanks! 

This should be available when registering a post type. 

You can assign as follows, if the post type is 'book'; 

`'application.posts.book.show-in-rest' => true`

Let me know if that's working for you.

**Comment by dooke** [comment]
Thank you!! It works.

So initial var / key in array have to replace '_' by '-'
`show_in_rest` 
with
`show-in-rest`

**Comment by darrenjacoby** [comment]
Good to hear! It should work either way actually, but I'll test again to make sure that's the case.
