### ISSUE TITLE
Question: Why use update_option instead of pre_option_{$option} filter

### ISSUE THREAD

**Issue by claytoncollie** [soberwp/intervention#64]
This is a very nice plugin and something I have been looking for for a long time. Great job. I did have a general question tho. Why are you updating the database all of the time with `update_option` calls. Why not use the `pre_option_{$option}` filter to short circuit the database call? Seems like it would improve performance and also log the options down to whatever you set in your array.

https://developer.wordpress.org/reference/hooks/pre_option_option/

**Comment by darrenjacoby** [comment]
Hey @claytoncollie,

I'm open to the suggestion of changing to `pre_option`, initially I wanted to update the DB value, but perhaps that's not necessary. What's your thoughts? I'm trying to preempt any downsides to using `pre_option` for users.

**Comment by claytoncollie** [comment]
I have not used this package yet so this is only thinking out loud. If you enabled all options in your config array then went to random pages in the wp-admin with Query Monitor turned on, you could see how many queries are being generated on each page load. My thought is that you are performing 2 database actions for each page load for each option. First to make the `update_option` call, then the standard `get_option` call afterward. With `pre_option_` it might be able to get rid of both. The only problem is that your database is not a source of truth anymore when you export for some reason. Pushing and pulling between environments would be fine if the codebase is version controlled, but your DB could potentially be "out of date" to what your config is.

My original question was to see if any thought was given to it and if using `update_option` was a conscious decision. Sounds like it was when you first started the project. I don't know the project well enough if you can give the option to filter the option or update the database.

**Comment by darrenjacoby** [comment]
Hey @claytoncollie,

Let me give it some more thought and do a little prototyping, perhaps an approach that uses both, only updating the DB at certain intervals, or on the dashboard/settings pages, or a version of that, and `pre_option` otherwise. I feel like that would be a win-win.

**Comment by pacotole** [comment]
Yes, I have the same question.

In principle, the `pre_option_{$option}` seems better, which bypass all the logic of the `get_option` function and returns the desired value. The downside is that you lose all settings when exporting or if you need to disable Intervention.

The `update_option` store your config on DB and solves previous downside. It should really only update on the first page load because `update_option` compares the values and if they are equal, they are not updated and there is no database hit. But there is a problem with numeric values: they are strictly compared with DB (string) value and always return false so forces an DB update on every page load.

I have actually added a filter that prevents this problem on [this branch](https://github.com/pacotole/intervention/commit/bc1f2b31e68ef6e10e6938aab83f45b486da2acd) (I'm not sure if it's the best file to add this code) and stops with DB updates on every load.

I am open to suggestions to modify it or to make a pull request 🙂

**Comment by darrenjacoby** [comment]
Hey @pacotole,

This looks great, thank you! I think having it in that file is perfect. 

I'll do some prototyping with `update_option` and `pre_option`. Another line of thought could be comparing the application config with a temp version, and if there are changes to the config, update the DB and update the temp version. Then we wouldn't even really need `pre_option`, while also removing unnecessary requests. Thoughts?

**Comment by claytoncollie** [comment]
I like the pre_option way of doing it b/c you can see it easier in the codebase. People understand how it relates to WordPress but using a core function. By doing an array compare, you are introducing custom logic that might be foreign to outsiders. You are also introducing a storage place for the temp version. Where does that get stored? Can it be lost or corrupted? How can you delete it when needed?

**Comment by claytoncollie** [comment]
I like the pre_option way of doing it b/c you can see it easier in the
codebase. People understand how it relates to WordPress but using a core
function. By doing an array compare, you are introducing custom logic that
might be foreign to outsiders. You are also introducing a storage place for
the temp version. Where does that get stored? Can it be lost or corrupted?
How can you delete it when needed?

*Clayton Collie*
***@***.***
214-577-6712

**Comment by darrenjacoby** [comment]
Yea, fair points that I agree with, thanks for thinking that through. Alright, so let’s go with `pre_option` and an occasional DB request! I’ll take a look at getting it changed soon.

**Comment by nlemoine** [comment]
I'm all with @claytoncollie here. `pre_option` seems the better option IMO. I think it's fair to assume that using the plugin is short cutting options handling and obviously deactivating it will result in falling back to default, unchanged, database options. Describing clearly that behavior in the readme should be enough.

Maybe the best option would be to introduce to [manually set options](https://github.com/danielbachhuber/dictator) to DB if needed?

**Comment by darrenjacoby** [comment]
Yea, I reckon I'm on the same page with `pre_option`. Had a pretty busy last two weeks with contract work, but will get to this soon.

**Comment by darrenjacoby** [comment]
This has been addressed in [d5ee64 ](https://github.com/soberwp/intervention/commit/d5ee64775215145cf9c4854fa30b2487164e2903) with a new internal Options API.
