### ISSUE TITLE
Labels translations

### ISSUE THREAD

**Issue by jmerilainen** [soberwp/intervention#66]
I was wondering if the function order related to translations in `src/Application/Support/Posttypes/Labels.php` and `src/Application/Support/Taxonomies/Labels.php` is intended as it is now? So currently the `sprintf` method is called inside `__` function – for example ` __(sprintf('Add New %s', $this->one), $i18n)`. 

This makes the making of the translation bit hard because all post types should be translated separately (like `Add New Posttype1`, `Add New Posttype2`) and the pot-file generators doesn't pick strings like `__(sprintf(...`.

I would suggest changing the order to be `sprintf(__('Add New %s', $i18n), $this->one)` so that it's easier to make translations.

I have tested the change locally already so I can contribute the change if you feel the change is alright.

(And thanks for making the plugin, really needed and has great features! 🙏)

**Comment by darrenjacoby** [comment]
Hey @jmerilainen ,

Thanks for reporting this, happy to accept a PR for this if you don't mind sending that through!
