### ISSUE TITLE
Comments remove `WP_Scripts::localize ` error

### ISSUE THREAD

**Issue by jmerilainen** [soberwp/intervention#67]
I was testing the new awesome `application.discussion => false` feature and noticed that it calls the `Comments::remove()` which calls `BlockEditor::set('discussion', true)`  and finally it will call ` wp_localize_script('intervention-block-editor', 'config', 'discussion')`. But the `wp_localize_script` function requires the last parameter to be array so it errors out.

Should the `BlockEditor::set('discussion', true)` be removed or have different value? (Or if it is still working progress, sorry to rush :D)

**Comment by darrenjacoby** [comment]
Hey @jmerilainen ,

I wasn't able to re-create the error, but did make a change, would you mind testing on your side for me? 

[b58bd8](https://github.com/soberwp/intervention/commit/b58bd8c17fad6997ce4f3415b769d91284f88961#diff-c0e42c354ace57697c49b4ac4be5e0cde566095cc8b356d0d72e1f02ce14d12c)

**Comment by darrenjacoby** [comment]
@jmerilainen just checking in here, let me know.

**Comment by jmerilainen** [comment]
Hey @darrenjacoby,

Sorry for ghosting suddenly, other things got over the way.

Yeah the format is now alright! But I still caught a minor error on front end which is missing dependencies of `intervention-block-editor` script. It requires `wp-blocks, wp-edit-post` scripts but I think those are enqueued only on admin.

I'm not yet super familiar with the codebase but for example this did the trick: 

```php
if (is_admin()) {
    BlockEditor::set(['discussion']);
}
```

**Comment by darrenjacoby** [comment]
@jmerilainen thanks, added into `BlockEditor.php` and will release soon!
