### ISSUE TITLE
Composer dependencies in /dist

### ISSUE THREAD

**Issue by nlemoine** [soberwp/intervention#68]
Hi, 

Any reason for composer dependencies to be included in the dist folder? It's loading unused/dev dependencies and those are messing with my composer dependencies.

Would you consider moving those to require-dev and not adding them to the releases?

**Comment by darrenjacoby** [comment]
@nlemoine sure yes! I think we only need `tightenco` in the dist folder, will test and confirm. Is there a particular dev dependency giving an issue for your use-case?

**Comment by nlemoine** [comment]
Thanks!

BTW the way, since it's WordPress and you're using composer, it's usually a good practice to prefix your dependencies because someone might use the same package in a different version. This may lead to conflicts/errors.

See [Yoast SEO](https://github.com/Yoast/wordpress-seo) (they use [`humbug/php-scoper`](https://github.com/humbug/php-scoper)) or [WP Rocket](https://github.com/wp-media/wp-rocket) (they use [`coenjacobs/mozart`](https://github.com/coenjacobs/mozart))

**Comment by darrenjacoby** [comment]
Thanks, will look into getting one of these options implemented!

**Comment by darrenjacoby** [comment]
Merged #69, thanks @nlemoine!

**Comment by nlemoine** [comment]
Thanks!
