### ISSUE TITLE
current_user_can before plugins_loaded

### ISSUE THREAD

**Issue by Soean** [soberwp/intervention#7]
If I call `intervention('remove-update-notices');` I get an error.

>Call to undefined function wp_get_current_user()
 
This is because the `current_user_can()` check is to early.

> The only prerequisite for current_user_can() is an existing wp_get_current_user(). The latter is defined in pluggable.php, so you can use it after plugins_loaded.

source: http://wordpress.stackexchange.com/questions/198185/what-is-valid-timing-of-using-current-user-can-and-related-functions

**Comment by darrenjacoby** [comment]
I'm not able to reproduce this, does https://github.com/soberwp/intervention/pull/6/commits/4517f24c65c0f51458c9b58a7e7459d710b207c4 fix it for you? 

Can we use admin_init rather than admin_menu for the action?

**Comment by Soean** [comment]
No, the pull request is not related to this. Its another issue. 
I try to reproduce this in an other installation.

**Comment by Soean** [comment]
My function call was in a plugin without an action hook. So, now with an init hook it works, thanks...

**Comment by darrenjacoby** [comment]
Cool, I've merged the other.  Let me know if you can recreate the error on `wp_get_current_user()
`
