### ISSUE TITLE
Feature: option to disable admin email verification screen

### ISSUE THREAD

**Issue by huubl** [soberwp/intervention#77]
Hi,

What do think about adding an option to disable the admin email verification screen?

See: [https://www.intelliwolf.com/disable-wordpress-admin-email-verification/](https://www.intelliwolf.com/disable-wordpress-admin-email-verification/)

Maybe something like:

```
return [
    'application' => [
        'general' => [
            ...
            'admin-email' => 'example@soberwp.com',
            'admin_email_check_interval' => false,
            ...
        ],
    ],
];
```

**Comment by darrenjacoby** [comment]
I like it! I would probably add it under `wp-admin.login.email-verification` as it only alerts on login if I'm correct?

**Comment by huubl** [comment]
Yes, as far as I know it only alerts on login. 

I have made a pull request. I added it under `wp-admin.login` as `admin-email-check-interval`, which can be used to change the interval or completely disable it. When the `admin-email` is set in `intervention.php`, I set it to disable automatically.

I not sure if fits [here](https://github.com/soberwp/intervention/blob/c60ab43542d6311b06501480a5fd98fcdc1cf213/.github/wp-admin/login.md), because the current settings are about the appearance of login and can set depending the role?

What do you think?

**Comment by darrenjacoby** [comment]
Thanks! Yea, still debating myself where this should belong. It's a tricky one because it feels like we're removing the login validation screen, however we're also setting an application option. I'll try pull in the changes and see what feels more natural.

**Comment by darrenjacoby** [comment]
Added to `application.general.admin-email.verification`

Thanks!
