### ISSUE TITLE
Dump settings out of an existing WordPress installation

### ISSUE THREAD

**Issue by conatus** [soberwp/intervention#81]
Hey all,

Great idea for some code. Reminds me of a more comprehensive and automatic version of [Dictator](https://github.com/boxuk/dictator), which allows declarative WordPress environments to be set up.

My question is: is there a way to dump out existing settings from WordPress then have the array created automatically for you?

If not right now, is this a planned piece of functionality?

Thanks so much in advance.

**Comment by darrenjacoby** [comment]
Hey Alex, 

That's a great idea, I'm going to be putting quite a bit more work in the coming months and can see the usefulness of this. 

I'll close the issue for now but have added it to the todo list and hope to get it implemented some time in the future.

**Comment by conatus** [comment]
Thanks @darrenjacoby!

If you could give this issue a little link so I get a notification whenever you get round to it I'd really appreciate it.

**Comment by darrenjacoby** [comment]
@conatus https://twitter.com/withjacoby/status/1432628725036769284
