### ISSUE TITLE
Need help to install plugin

### ISSUE THREAD

**Issue by aitormendez** [soberwp/intervention#83]
Hi, @darrenjacoby. I am unable to install the plugin correctly on Bedrock / Sage10. First of all, I try it with Composer, but the macOS PHP version is 7.3.24 (Vagrant box has 7.4.21):

```
 [InvalidArgumentException]
 Package soberwp / intervention at version dev-master has a PHP requirement in compatible with your PHP version, PHP extensions and Composer version:
     - soberwp / intervention requires php ^ 7.4 | ^ 8.0 which does not match your i nstalled version 7.3.24.
     - soberwp / intervention requires tightenco / collect ^ 8 but it is not present.
```

Second, I try the wp-cli command. After installation I get this warning:

> Warning: require(/srv/www/arte-conocimiento.com/current/web/app/plugins/intervention/dist/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /srv/www/arte-conocimiento.com/current/web/app/plugins/intervention/dist/composer/autoload_real.php on line 69
> 
> Fatal error: require(): Failed opening required '/srv/www/arte-conocimiento.com/current/web/app/plugins/intervention/dist/composer/../symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/usr/share/php') in /srv/www/arte-conocimiento.com/current/web/app/plugins/intervention/dist/composer/autoload_real.php on line 69

I'm not sure what the problem is. Could you suggest a diagnosis / solution? Thank you!

**Comment by darrenjacoby** [comment]
Hey @aitormendez,

Looks like the php requirement is not being met. The WP CLI error looks strange, I’ll test that out first thing tomorrow.

**Comment by aitormendez** [comment]
Updating macOS PHP fix the composer installation way and the plugin works fine. Big Sur comes with PHP 7.3 by default.

**Comment by darrenjacoby** [comment]
Hey @aitormendez, glad to hear you got it working, thanks for reporting back.
