### ISSUE TITLE
Docker + Roots wrong composer inclusion path

### ISSUE THREAD

**Issue by mrgesco** [soberwp/intervention#84]
Hi,

I'm trying to add this plugin in my bedrock/roots installation with no success.

The problem is that composer tries to load the main file but at the wrong place.

I'm using docker to get a development stack (PHP-APACHE-MYSQL) and the web folder in the docker is `/var/www/html` mapped with `web` of bedrock/roots

`/var/www/vendor/composer/../../web/app/plugins/intervention/src/Intervention.php`

should have been

`/var/www/vendor/composer/../../--->html<----/app/plugins/intervention/src/Intervention.php`

Have you any idea or advice to make this working?

Thanks for any help

**Comment by darrenjacoby** [comment]
@mrgesco I'll retest with Bedrock, but initial feeling is that it may have something do with the setup.

The path is loaded using `define('INTERVENTION_DIR', dirname(__FILE__)); ` which runs from `intervention.php` within the plugin folder and should return the correct path for loading files from there. You could try echo constant `INTERVENTION_DIR` and see what it returns?

**Comment by mrgesco** [comment]
Thank you @darrenjacoby for your quick reply!

This is the value of `INTERVENTION_DIR` and the plugin is working
`/var/www/html/app/plugins/intervention`

But I have always the warning about composer
`include(/var/www/vendor/composer/../../web/app/plugins/intervention/src/Intervention.php): failed to open stream: No such file or directory /var/www/vendor/composer/ClassLoader.php:444`

**Comment by darrenjacoby** [comment]
@mrgesco try give `rc.4` a go, tagged today and let me know if that helps.

**Comment by mrgesco** [comment]
No luck same behavior.

Getting the plugin manually works fine without the warning.

I'm pretty sure the problem is with docker but can't figure why...

Plugins required from wpackagist works fine.

**Comment by mrgesco** [comment]
Unfortunatly not. I have installed the plugin manually and not with composer

**Comment by darrenjacoby** [comment]
Thanks for reporting back @mrgesco. I haven't been able to replicate, so I'm going to close for now. If you discover any more information regarding the issue please do let me know.
