### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by bigskillet** [soberwp/intervention#85]
> Warning: require(/wp-content/plugins/intervention/dist/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /wp-content/plugins/intervention/dist/composer/autoload_real.php on line 69

PHP 7.4.14
Intervention 2.0.0-rc.3
WordPress 5.7.2

**Comment by darrenjacoby** [comment]
Hey @bigskillet ,

Can you give dev-master a go? Should be fixed now.  I'll tag rc-4 shortly.

**Comment by bigskillet** [comment]
That worked! Appreciate the quick reply!
