### ISSUE TITLE
Noob trouble trying to get Intervention working.

### ISSUE THREAD

**Issue by jonsherrard** [soberwp/intervention#88]
Forewarning, I am likely being a complete dolt here but I can't get this to work.

I've installed a must-use plugin through composer. The plugin itself is being loaded (I did a trusty `echo "test"; exit;`, to check), but the intervention.php file I've included in the root of my theme doesn't seem to be being loaded.

```sh
- ~
-   app
  -  themes
    - my-theme
      - intervention.php
```

I've got the following in `intervention.php`

```php
<?php

return [
    'wp-admin.all' => [
        'dashboard' => 'posts',
    ],
];
```

And naturally I'm expecting the dashboard menu to be removed and redirect to posts, but no dice.

Anything glaringly incorrect in this setup? Any help welcome 😢

**Comment by darrenjacoby** [comment]
Hey @jonsherrard,

It sounds like it's not finding the intervention.php file, are you using Sage 9/10?

**Comment by jonsherrard** [comment]
Hi @darrenjacoby I am not, is it required? 😬

**Comment by darrenjacoby** [comment]
Nope it's not, it would just read from either `resources/` or `config/` if you were. it uses `get_stylesheet_directory()`, what does that return for you if you run somewhere in your code?

**Comment by jonsherrard** [comment]
Hi @darrenjacoby,

I've figured it out. Installing with `composer require` defaults to version 1.3, which wasn't working. Discovered this when I searched the installed plugin for `get_stylesheet_directory` and it wasn't there.

Updated my composer to install directly from the master branch and everything's working perfectly 👍

**Comment by darrenjacoby** [comment]
Ah right, that's an easy oversight. I need to tag 2.0.0, but been working on a few extra things for the release.

**Comment by jonsherrard** [comment]
Thanks for your help! Amazing project too.

**Comment by darrenjacoby** [comment]
@jonsherrard, thanks so much for the beers! It was so unexpected and made my day. 🍻🍻🍻
