### ISSUE TITLE
Something goes wrong setting options / saving to database

### ISSUE THREAD

**Issue by huubl** [soberwp/intervention#89]
Hi,

Something goes wrong when using this settings:

```
<?php
use function Env\env;

return [
    'application' => [
        'general' => [
            'site-title' => 'My website',
            'wp-address' => env('WP_SITEURL'),
            'site-address' => env('WP_HOME'),
            'admin-email' => 'my@email.com',
            'admin-email.verification' => false,
            'email-from' => 'info@mysite.nl',
            'email-from-name' => 'My website',
            'membership' => false,
            'default-role' => 'subscriber',
            'language' => 'nl_NL',
            'timezone' => 'Europe/Amsterdam',
            'date-format' => 'j F Y',
            'time-format' => 'H:i',
            'week-starts' => 'Mon',
        ],
        'writing' => [
            'emoji' => false,
            'default-category' => 1,
            'default-post-format' => 'standard',
            'post-via-email.server' => 'mail.example.com',
            'post-via-email.port' => 110,
            'post-via-email.login' => 'login@example.com',
            'post-via-email.pass' => 'password',
            'post-via-email.default-category' => 1,
            'update-services' => 'http://rpc.pingomatic.com/',
        ],
        'reading' => [
            'front-page' => 2,
            'front-page.posts' => 454,
            'posts-per-page' => 9,
            'posts-per-rss' => 9,
            'rss-excerpt' => 'summary',
        ],
        'media' => [
            'sizes.thumbnail' => [
                'width' => 300,
                'height' => 200,
                'crop' => true,
            ],
            'sizes.medium' => [
                'width' => 640,
                'height' => 480,
            ],
            'sizes.large' => [
                'width' => 1100,
                'height' => 800,
            ],
            'uploads.organize' => true,
        ],
        'permalinks' => [
            'structure' => '/nieuws/%year%/%monthnum%/%day%/%postname%/',
            'category-base' => 'nieuws/categorie',
            'tag-base' => 'nieuws/tag',
        ],
        'privacy.policy-page' => 2731,
    ],
];
```

When I check the database values, they are not changing or (when I click save on the admin general settings page ) wrong. For example the media options get:

option_name | option_value | autoload
-- | -- | --
thumbnail_size_w | 0 | no
thumbnail_size_h | 0 | no
thumbnail_crop | 1 | no
medium_size_w | 0 | no
medium_size_h | 0 | no

When saving the (partly) locked setting on the admin general settings page (by the save button ) and then comment out the application -> general settings I get this:

![image](https://user-images.githubusercontent.com/50170696/130224570-2b3c8f49-bb1b-4558-9f15-482d024888de.png)

Am I doing something wrong?

- Using Intervention dev-master branch (loaded as mu-plugin)
- Bedrock / Sage 10

**Comment by darrenjacoby** [comment]
Hey @huubl,

I’m on my phone now, but the new versions use pre_option which is faster than updating the db, so it wouldn’t reflect in the db itself. I am working on providing a sync option to update the db, should be releasing that soon.

**Comment by darrenjacoby** [comment]
Hey @huubl,

Just tested with a new copy from dev-master here and no problems with the above config. 

Are you using any other plugins that could be changing wp-admin settings elements? The design looks different to standard WP, so just wondering if that could be playing into it. 

![image](https://user-images.githubusercontent.com/15921694/130241125-0687486c-227d-414c-b554-210e94047313.png)

**Comment by darrenjacoby** [comment]
@huubl ,

Interesting, I was finally able to replicate. The problem is that Intervention is setting fields in `application` as disabled on the option pages, and so when you save settings from WP, the disabled field values aren't pulling through on save and instead clearing the DB entries. Not ideal. I think change from `disabled` to `readonly` will work better, but still testing.

**Comment by darrenjacoby** [comment]
Really appreciate you picking this up, got a hotfix up which should solve it. Let me know if it does it for you. https://github.com/soberwp/intervention/commit/cf57d4a7ac3611174146ae118984bbcad818f3f5

**Comment by jmerilainen** [comment]
Related to the fix: the `Sober\Intervention\UserInterface\Tools\Import` class is missing from the repo.

**Comment by darrenjacoby** [comment]
@jmerilainen ah thanks! fixed.

**Comment by huubl** [comment]
Hi @darrenjacoby,

I missed #64 Intervention using the pre_option now. I tried the current master branch with hotfix and it solves the problem.

Thanks for looking in to this!
